/** 공식 일곱 문서에서 확인한 기술 item 116개를 로컬 섹션과 1:1로 묶어 coverage 근거로 남긴다. */

/** 어떤 공식 문서의 어떤 주장이 어느 섹션에서 설명되는지를 한 행으로 고정한다. */
export type SourceItem = {
  id: string
  officialItem: string
  source: 'gsap-timeline' | 'timeline' | 'timeline-vars' | 'timeline-to' | 'timeline-from' | 'timeline-from-to' | 'timeline-set'
  /** 공식 문서에 게시된 주장인지, 설치본 실행으로만 확인한 사실인지 구분한다. */
  origin: 'official' | 'implementation'
  sectionId: string
}

/** Timeline 생성과 child 추가에 관한 기술 주장 전체 목록 — PageCoverage와 각 섹션이 같은 배열을 센다. */
export const timelineBasicsSourceItems: SourceItem[] = [
  // 01 why-timeline — 8
  { id: 'GT-01', officialItem: 'gsap.timeline()의 반환 표기는 Returns : Timeline이다.', source: 'gsap-timeline', origin: 'official', sectionId: 'why-timeline' },
  { id: 'GT-02', officialItem: 'Timeline은 tween과 다른 timeline을 담는 컨테이너로 동작하는 강력한 sequencing 도구이며, 전체를 하나로 제어하고 타이밍을 정밀하게 관리하기 쉽게 만든다.', source: 'gsap-timeline', origin: 'official', sectionId: 'why-timeline' },
  { id: 'GT-03', officialItem: 'Timeline이 없으면 복잡한 sequence 만들기가 훨씬 번거롭다. animation마다 delay를 써야 하기 때문이다. 공식 "WITHOUT Timelines" 예제는 delay 없음 · delay 1 · delay 2를 차례로 적는다.', source: 'gsap-timeline', origin: 'official', sectionId: 'why-timeline' },
  { id: 'GT-04', officialItem: '첫 animation을 더 길게 만들려면 그 뒤의 모든 delay를 고쳐야 한다. 게다가 전체를 pause() · restart() · reverse()하거나 두 번 반복시키려 하면 코드가 지저분해진다.', source: 'gsap-timeline', origin: 'official', sectionId: 'why-timeline' },
  { id: 'GT-05', officialItem: '공식 "WITH Timelines" 예제는 var tl = gsap.timeline({repeat: 2, repeatDelay: 1})로 만든 뒤 tl.to()를 세 번 부르고, tl.pause() · tl.resume() · tl.seek(1.5) · tl.reverse()로 전체를 한 번에 제어한다.', source: 'gsap-timeline', origin: 'official', sectionId: 'why-timeline' },
  { id: 'GT-06', officialItem: '이제 delay가 줄줄이 딸려 바뀌는 걱정 없이 타이밍을 조절할 수 있다. 첫 tween의 duration을 늘리면 나머지가 자동으로 맞춰진다.', source: 'gsap-timeline', origin: 'official', sectionId: 'why-timeline' },
  { id: 'TL-01', officialItem: 'Quick Start의 Minimal usage 예제는 gsap.to(".box", { rotation: 27, x: 100, duration: 1 })을 "이것이 Tween"으로, let tl = gsap.timeline() 뒤에 .to()를 세 번 이어 붙인 것을 "sequence된 tween 세 개를 담은 Timeline"으로 나란히 보여 준다.', source: 'timeline', origin: 'official', sectionId: 'why-timeline' },
  { id: 'TL-02', officialItem: 'Timeline 클래스 페이지는 gsap.timeline() 페이지와 같은 여섯 개 기술 절(Positioning · Special Properties and Callbacks · Setting Defaults · Nesting · Other Timeline Features · How do timelines work?)을 그대로 다시 싣고, "WITHOUT Timelines" 예제만 duration 2 · delay 3으로 다르게 적는다.', source: 'timeline', origin: 'official', sectionId: 'why-timeline' },

  // 02 timeline-instance — 9
  { id: 'TV-00', officialItem: 'signature는 vars : Object이며, gsap.timeline({onComplete: func})처럼 constructor를 통해 원래 timeline에 넘긴 설정 객체다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-instance' },
  { id: 'TV-01', officialItem: 'Details — constructor에 넘긴 vars 객체이며, timeline이 갖기를 원하는 property와 value 전부를 담고 있다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-instance' },
  { id: 'TL-03', officialItem: 'Properties 표 autoRemoveChildren : Boolean — true면 자식 tween과 timeline이 완료되는 즉시 제거된다.', source: 'timeline', origin: 'official', sectionId: 'timeline-instance' },
  { id: 'TL-04', officialItem: 'Properties 표 data : * — 원하는 데이터를 저장해 두는 자리이며 vars.data가 있으면 그 값으로 초기에 채워진다.', source: 'timeline', origin: 'official', sectionId: 'timeline-instance' },
  { id: 'TL-05', officialItem: 'Properties 표 labels : Object — timeline에 추가된 label들을 저장한다.', source: 'timeline', origin: 'official', sectionId: 'timeline-instance' },
  { id: 'TL-06', officialItem: 'Properties 표 parent : Timeline — animation이 붙어 있는 부모 Timeline이다. 직접 만든 Timeline에 넣지 않은 것은 모두 기본적으로 gsap.globalTimeline에 놓인다.', source: 'timeline', origin: 'official', sectionId: 'timeline-instance' },
  { id: 'TL-07', officialItem: 'Properties 표 scrollTrigger: ScrollTrigger | undefined — timeline에 연결된 ScrollTrigger에 접근하는 편리한 방법이며 timeline이 ScrollTrigger를 가지고 있을 때만 접근할 수 있다.', source: 'timeline', origin: 'official', sectionId: 'timeline-instance' },
  { id: 'TL-08', officialItem: 'Properties 표 smoothChildTiming : Boolean — 실행 중 property가 바뀔 때 매끄러운 재생을 유지하려고 자식 tween·timeline의 startTime을 자동으로 다시 배치할지 제어한다.', source: 'timeline', origin: 'official', sectionId: 'timeline-instance' },
  { id: 'TL-09', officialItem: 'Properties 표 vars : Object — gsap.timeline({onComplete: func})처럼 constructor를 통해 원래 timeline에 넘긴 설정 객체다.', source: 'timeline', origin: 'official', sectionId: 'timeline-instance' },

  // 03 timeline-vars — 24
  { id: 'GT-07', officialItem: 'Special Properties and Callbacks — vars 객체에 아래 항목을 아무거나 넣어 animation에 특별한 능력을 줄 수 있다. 공식 예제는 gsap.timeline({ onComplete: myFunction, repeat: 2, repeatDelay: 1, yoyo: true })이다.', source: 'gsap-timeline', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'GT-08', officialItem: '"All of timeline\'s vars properties are described below" — 이어지는 Property/Description 목록이 timeline vars 전체이며 항목은 22개다.', source: 'gsap-timeline', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-02', officialItem: 'autoRemoveChildren — Boolean. true면 자식 tween·timeline이 완료되는 즉시 kill·제거된다. 시간을 거슬러 갈 수 없게 되므로(reverse()나 progress를 낮추는 경우) 보통은 바람직하지 않지만 속도와 메모리 관리에는 도움이 된다. root timeline들은 autoRemoveChildren: true를 쓴다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-03', officialItem: 'callbackScope — Object. onStart·onUpdate·onComplete 등 모든 callback에서 쓰일 scope이며, callback 안의 this가 가리키는 대상이다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-04', officialItem: 'defaults — Object. 자식 animation이 상속하는 기본값을 지정하는 간단한 방법이며 "defaults" 절에 자세한 내용이 있다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-05', officialItem: 'delay — Number. animation이 시작되기 전 대기하는 시간(초)이다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-06', officialItem: 'onComplete — Function. animation이 완료됐을 때 호출되는 함수다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-07', officialItem: 'onCompleteParams — Array. onComplete 함수에 넘길 파라미터 배열이다. 예: gsap.timeline({onComplete: myFunction, onCompleteParams: ["param1", "param2"]}).', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-08', officialItem: 'onInterrupt — 타입 칸이 비어 있다. animation이 중간에 중단됐을 때 호출할 함수이며, 정상적으로 완료된 경우에는 실행되지 않는다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-09', officialItem: 'onInterruptParams — 타입 칸이 비어 있다. onInterrupt 함수에 넘길 파라미터 Array다. 예: gsap.to(".class", {x:100, onInterrupt:myFunction, onInterruptParams:["param1", "param2"]}).', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-10', officialItem: 'onRepeat — Function. animation이 반복될 때마다 호출되는 함수다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-11', officialItem: 'onRepeatParams — Array. onRepeat 함수에 넘길 파라미터 Array다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-12', officialItem: 'onReverseComplete — Function. animation이 역방향으로 다시 시작 지점에 도달했을 때 호출된다. reverse()를 부르면 tween이 시작 쪽으로 되돌아가고 time이 0이 될 때 실행된다. 이 animation을 담은 timeline이 reverse돼 시작 지점까지(또는 그 너머로) 되감길 때도 일어난다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-13', officialItem: 'onReverseCompleteParams — Array. onReverseComplete 함수에 넘길 파라미터 배열이다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-14', officialItem: 'onStart — Function. animation이 시작될 때 호출된다. time이 0에서 다른 값으로 바뀔 때이며, tween을 여러 번 restart하면 여러 번 일어날 수 있다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-15', officialItem: 'onStartParams — Array. onStart 함수에 넘길 파라미터 배열이다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-16', officialItem: 'onUpdate — Function. animation이 갱신될 때마다(활성 상태인 매 frame) 호출된다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-17', officialItem: 'onUpdateParams — Array. onUpdate 함수에 넘길 파라미터 배열이다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-18', officialItem: 'paused — Boolean. true면 animation이 생성 즉시 스스로 일시정지한다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-19', officialItem: 'repeat — Number. 첫 재생 이후 반복할 횟수다. repeat가 1이면 총 두 번 재생된다(최초 재생 + 1회 반복). 무한 반복은 -1이며 repeat는 항상 정수여야 한다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-20', officialItem: 'repeatDelay — Number. 반복 사이의 대기 시간(초)이다. repeat가 2이고 repeatDelay가 1이면 재생 → 1초 대기 → 재생 → 1초 대기 → 마지막 반복 순서로 진행된다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-21', officialItem: 'repeatRefresh — 타입 칸이 비어 있다. repeatRefresh: true면 반복하는 timeline이 매 전체 반복마다(yoyo는 제외) 자식 tween 전부를 invalidate()하고 시작·끝 값을 내부적으로 다시 기록한다. relative·random·function-based 같은 동적 값을 쓸 때 유용하다. 예를 들어 x: "random(-100, 100)"은 반복마다 새 x 값을 받는다. duration·delay·stagger는 refresh되지 않는다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-22', officialItem: 'smoothChildTiming — Boolean. 타이밍 관련 property가 실행 중에 바뀔 때 매끄러운 재생을 유지하려고 자식 animation의 startTime을 자동으로 다시 배치할지 제어한다. timeline의 playhead가 75% 진행된 자식 tween 위에 있는데 그 tween의 reverse()가 호출된 경우, smoothChildTiming이 false면(globalTimeline을 제외한 기본값) tween이 startTime을 유지한 채 제자리에서 뒤집혀 timeline playhead가 75% 지점이 아니라 25% 지점에 놓이게 된다. "How do timelines work?" 절에 자세한 내용이 있다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },
  { id: 'TV-23', officialItem: 'yoyo — Boolean. true면 반복 주기마다 방향이 번갈아 바뀌어 앞뒤로 오가는 것처럼 보인다. reversed property에는 영향을 주지 않는다. repeat가 2이고 yoyo가 false면 1-2-3-1-2-3-1-2-3, true면 1-2-3-3-2-1-1-2-3처럼 보인다.', source: 'timeline-vars', origin: 'official', sectionId: 'timeline-vars' },

  // 04 child-creators — 37
  { id: 'TT-01', officialItem: 'signature는 to( target:[ Object | Array | String ], vars:Object, position:[ Number | String ] ) : self 이다.', source: 'timeline-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TT-02', officialItem: 'gsap.to() tween을 timeline 끝에(또는 position 파라미터로 다른 곳에) 추가한다. add( gsap.to(...) )와 정확히 같은 일을 더 짧은 코드로 하는 편의 메서드다.', source: 'timeline-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TT-03', officialItem: 'target 인자 — property를 바꿀 대상 객체(또는 객체 배열)다. "#feature"나 "h2.author" 같은 CSS selector text도 된다. GSAP은 selector 문자열을 document.querySelectorAll()에 넘긴다.', source: 'timeline-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TT-04', officialItem: 'vars 인자 — animate할 각 property의 끝 값과 onComplete·ease 같은 special property를 담은 객체다.', source: 'timeline-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TT-05', officialItem: 'position 인자 — (default = "+=0") timeline 안의 삽입 지점을 제어한다. 기본은 timeline의 끝이다. 아직 없는 label을 적으면 그 label이 자동으로 timeline 끝에 추가된다.', source: 'timeline-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TT-06', officialItem: 'Returns : self — "self (makes chaining easier)". 반환값은 timeline 자신이며 chaining을 쉽게 하기 위한 것이다.', source: 'timeline-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TT-07', officialItem: 'Details 예제 — var tween = gsap.to(element, { duration: 1, x: 100, opacity: 0.5 }); tl.add(tween); 두 줄과 tl.to(element, { duration: 1, x: 100, opacity: 0.5 }) 한 줄이 같은 결과를 낸다.', source: 'timeline-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TT-08', officialItem: 'to() tween에서 쓸 수 있는 모든 세부 사항과 special property는 gsap.to() 문서를 보라고 안내한다.', source: 'timeline-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TT-09', officialItem: '이 호출들을 chaining하고 from() · call() · set() 같은 다른 편의 메서드와 함께 써서 sequence를 아주 빠르게 만들 수 있다. 공식 chaining 예제는 gsap.timeline({onComplete: myFunction}) 뒤에 from → to → set → call → to(stagger 포함) 순으로 이어 붙인다. set 위 주석은 opacity를 0.5로 만든다고 쓰지만 실제 코드는 { opacity: 0 }이다.', source: 'timeline-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TF-01', officialItem: 'signature는 from( target:[ Object | Array | String ], vars:Object, position:[ Number | String ] ) : self 이다.', source: 'timeline-from', origin: 'official', sectionId: 'child-creators' },
  { id: 'TF-02', officialItem: '.from() tween을 timeline 끝에(또는 position 파라미터로 다른 곳에) 추가한다. add( gsap.from(...) )와 정확히 같은 일을 더 짧은 코드로 한다.', source: 'timeline-from', origin: 'official', sectionId: 'child-creators' },
  { id: 'TF-03', officialItem: 'vars 인자 — tween할 각 property의 시작 값과 onComplete·ease 같은 special property를 정의한 객체다.', source: 'timeline-from', origin: 'official', sectionId: 'child-creators' },
  { id: 'TF-04', officialItem: 'target 인자 — property를 바꿀 대상 객체(또는 객체 배열)이며 CSS selector text도 되고 GSAP이 document.querySelectorAll()에 넘긴다.', source: 'timeline-from', origin: 'official', sectionId: 'child-creators' },
  { id: 'TF-05', officialItem: 'position 인자 — (default = "+=0") 삽입 지점을 제어하고 기본은 timeline의 끝이며, 없는 label을 적으면 끝에 자동 추가된다.', source: 'timeline-from', origin: 'official', sectionId: 'child-creators' },
  { id: 'TF-06', officialItem: 'Returns : self — "self (makes chaining easier)".', source: 'timeline-from', origin: 'official', sectionId: 'child-creators' },
  { id: 'TF-07', officialItem: 'Details 예제 — gsap.from(element, { duration: 1, x: 100, opacity: 0.5 })을 add()로 넣는 두 줄과 tl.from(...) 한 줄이 같은 결과를 낸다. 세부 사항은 gsap.from() 문서로 안내한다.', source: 'timeline-from', origin: 'official', sectionId: 'child-creators' },
  { id: 'TF-08', officialItem: 'to() · call() · set() 등과 chaining해 sequence를 빠르게 만들 수 있다는 같은 안내와 chaining 예제를 싣는다.', source: 'timeline-from', origin: 'official', sectionId: 'child-creators' },
  { id: 'TF-09', officialItem: 'info — from() tween은 immediateRender가 기본적으로 true라서 지정한 delay와 무관하게 시작 상태를 즉시 render한다. vars에 immediateRender: false를 넘기면 tween이 실제로 시작될 때까지 render를 미룬다.', source: 'timeline-from', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-01', officialItem: 'signature는 fromTo( target:[ Object | Array | String ], fromVars:Object, toVars:Object, position:[ Number | String ] ) : self 이며 인자가 네 개다.', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-02', officialItem: '.fromTo() tween을 timeline 끝에 추가한다. add( gsap.fromTo(...) )와 정확히 같은 일을 더 짧은 코드로 한다.', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-03', officialItem: 'target 인자 — property를 바꿀 대상 객체(또는 객체 배열)이며 CSS selector text도 되고 GSAP이 document.querySelectorAll()에 넘긴다.', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-04', officialItem: 'fromVars 인자 — animate할 각 property의 시작 값을 정의한 객체다. duration · ease · delay 같은 special property는 여기 넣지 말고 toVars에 넣어야 한다.', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-05', officialItem: 'toVars 인자 — animate할 각 property의 끝 값과 duration · onComplete · ease 같은 special property를 정의한 객체다.', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-06', officialItem: 'position 인자 — (default = "+=0") 삽입 지점을 제어하고 기본은 timeline의 끝이며, 없는 label을 적으면 끝에 자동 추가된다.', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-07', officialItem: 'Returns : self — "self (makes chaining easier)".', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-08', officialItem: 'Details 예제 — var tween = gsap.fromTo(element, { x: -100 }, { duration: 1, x: 100 }); tl.add(tween); 두 줄과 tl.fromTo(element, { x: -100 }, { duration: 1, x: 100 }) 한 줄이 같은 결과를 낸다. 세부 사항은 gsap.fromTo() 문서로 안내한다.', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-09', officialItem: 'to() · call() · set() 등과 chaining해 sequence를 빠르게 만들 수 있다는 같은 안내와 chaining 예제를 싣는다.', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TFT-10', officialItem: 'info — fromTo() tween은 immediateRender가 기본적으로 true라서 지정한 delay와 무관하게 시작 상태를 즉시 render한다. vars에 immediateRender: false를 넘기면 실제로 시작될 때까지 render를 미룬다.', source: 'timeline-from-to', origin: 'official', sectionId: 'child-creators' },
  { id: 'TS-01', officialItem: 'signature는 set( target:[ Object | Array | String ], vars:Object, position:[ Number | String ] ) : self 이다.', source: 'timeline-set', origin: 'official', sectionId: 'child-creators' },
  { id: 'TS-02', officialItem: 'duration이 0인 tween을 timeline 끝에(또는 position 파라미터로 다른 곳에) 추가해, 가상 playhead가 그 위치에 도달하는 순간 값을 즉시 설정한다. add( gsap.to(target, {duration: 0, ...}) )와 정확히 같은 일을 더 짧은 코드로 한다.', source: 'timeline-set', origin: 'official', sectionId: 'child-creators' },
  { id: 'TS-03', officialItem: 'target 인자 — property를 설정할 대상 객체(또는 객체 배열)다. to() · from() · fromTo()와 달리 selector text와 document.querySelectorAll() 문장이 이 페이지에는 적혀 있지 않다.', source: 'timeline-set', origin: 'official', sectionId: 'child-creators' },
  { id: 'TS-04', officialItem: 'vars 인자 — 각 property를 어떤 값으로 설정할지 정의한 객체다. 예를 들어 element의 left를 100, top을 200으로 설정하려면 myTimeline.set(element, {left: 100, top: 200})이다.', source: 'timeline-set', origin: 'official', sectionId: 'child-creators' },
  { id: 'TS-05', officialItem: 'position 인자 — (default = "+=0") 삽입 지점을 제어하고 기본은 timeline의 끝이며, 없는 label을 적으면 끝에 자동 추가된다.', source: 'timeline-set', origin: 'official', sectionId: 'child-creators' },
  { id: 'TS-06', officialItem: 'Returns : self — "self (makes chaining easier)".', source: 'timeline-set', origin: 'official', sectionId: 'child-creators' },
  { id: 'TS-07', officialItem: 'Details 예제 — var setValues = gsap.set(element, { x: 100, opacity: 0.5 }); tl.add(setValues); 두 줄과 tl.set(element, { x: 100, opacity: 0.5 }) 한 줄이 같은 결과를 낸다. Details 본문은 heading 요약과 달리 add( gsap.set(...) )와 같다고 적고, 세부 사항은 gsap.set() 문서로 안내한다.', source: 'timeline-set', origin: 'official', sectionId: 'child-creators' },
  { id: 'TS-08', officialItem: 'to() · call() · from() 등과 chaining해 sequence를 빠르게 만들 수 있다는 같은 안내와 chaining 예제를 싣는다.', source: 'timeline-set', origin: 'official', sectionId: 'child-creators' },
  { id: 'TS-09', officialItem: '페이지 마지막 문장 — set()의 기본 immediateRender 값은 false이며, immediateRender에 대한 자세한 내용은 별도 글로 안내한다.', source: 'timeline-set', origin: 'official', sectionId: 'child-creators' },

  // 05 position-parameter — 19
  { id: 'GT-09', officialItem: '정교한 타이밍의 비결은 여러 Timeline 메서드에서 쓰이는 position parameter를 이해하는 것이다. 이 한 개의 유연한 파라미터가 tween · label · callback · pause, 심지어 중첩된 timeline의 배치까지 제어한다. 즉 timeline에게 animation을 정확히 어디에 넣을지 알려 준다. 보통 vars 파라미터 다음에 오며 여러 동작을 가진다.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'GT-10', officialItem: '절대 시간 — 3 같은 숫자. tl.to(".class", { x: 100 }, 3)은 timeline 시작에서 정확히 3초 지점에 넣는다.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'GT-11', officialItem: '상대 시간 — "+=1"이나 "-=1"이며 timeline의 끝을 기준으로 한다. "+=1"은 끝에서 1초 뒤에 넣어 간격을 만들고, "-=1"은 끝을 1초 겹치게 한다.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'GT-12', officialItem: 'label — "someLabel"처럼 적는다. 아직 존재하지 않으면 그 label이 timeline 끝에 추가된다.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'GT-13', officialItem: 'label 기준 상대 — "someLabel+=1"처럼 적는다. 공식 예제 "someLabel+=2"는 "someLabel" label에서 2초 뒤에 넣는다.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'GT-14', officialItem: '"<" — 가장 최근에 추가된 animation의 시작 지점에 넣는다.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'GT-15', officialItem: '">" — 가장 최근에 추가된 animation의 끝 지점에 넣는다.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'GT-16', officialItem: '"<1" — 가장 최근에 추가된 animation의 시작 기준 상대다. "<1"은 시작에서 1초 뒤, 음수인 "<-2"는 시작에서 2초 앞이다.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'GT-17', officialItem: '">1" — 가장 최근에 추가된 animation의 끝 기준 상대다. ">1"은 끝에서 1초 뒤, 음수인 ">-2"는 끝에서 2초 앞이다.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'GT-18', officialItem: 'Hint — "<"와 ">"를 가장 최근에 추가된 animation의 시작 또는 끝을 가리키는 포인터로 생각하라.', source: 'gsap-timeline', origin: 'official', sectionId: 'position-parameter' },
  { id: 'TT-10', officialItem: '기본적으로 animation은 timeline 끝에 추가돼 하나씩 차례로 sequence된다. position 파라미터로 정확한 배치를 제어할 수 있고, 보통 vars 파라미터 다음에 오며 유연한 문법을 쓴다.', source: 'timeline-to', origin: 'official', sectionId: 'position-parameter' },
  { id: 'TT-11', officialItem: '복합 문자열 — "+="와 "-=" 접두사가 상대값을 뜻한다. "<"나 ">" 뒤에 숫자가 오면 상대값으로 해석되므로 "<2"는 "<+=2"와 같다. 공식 예제 6개: "+=1"(끝에서 1초 뒤, 간격), "-=1"(끝에서 1초 앞, 겹침), "myLabel+=2", "<+=3"(이전 animation 시작에서 3초 뒤), "<3"("<+=3"과 같음), ">-0.5"(이전 animation 끝에서 0.5초 앞).', source: 'timeline-to', origin: 'official', sectionId: 'position-parameter' },
  { id: 'TT-12', officialItem: '퍼센트 기반 복합 문자열 — "+=" 또는 "-=" 바로 뒤에 오면 삽입되는 animation의 total duration 기준이고, "<" 또는 ">" 바로 뒤에 오면 이전 animation의 total duration 기준이다. total duration에는 repeat·yoyo가 포함된다. 공식 예제 5개: "-=25%", "+=50%", "<25%"(이전 animation 시작에서 25% 지점, ">-75%"와 같음), "<+=25%"(기준이 삽입되는 animation이라 "<25%"와 다름), "myLabel+=30%".', source: 'timeline-to', origin: 'official', sectionId: 'position-parameter' },
  { id: 'TT-13', officialItem: '퍼센트 기반 값은 GSAP 3.7.0에서 추가됐다.', source: 'timeline-to', origin: 'official', sectionId: 'position-parameter' },
  { id: 'TT-14', officialItem: '"previous animation"은 가장 최근에 삽입된 animation을 뜻하며, 반드시 timeline 끝에 가장 가까운 animation은 아니다.', source: 'timeline-to', origin: 'official', sectionId: 'position-parameter' },
  { id: 'TT-15', officialItem: 'Position Parameter Interactive Demo 절이 있고, 대화형 timeline 시각화와 영상이 포함된 Position Parameter 글을 꼭 읽으라고 안내한다.', source: 'timeline-to', origin: 'official', sectionId: 'position-parameter' },
  { id: 'TF-10', officialItem: 'from() 페이지도 "Positioning animations in a timeline" 절을 같은 내용으로 그대로 싣는다. 예제 코드는 tl.to(...) 형태 그대로다.', source: 'timeline-from', origin: 'official', sectionId: 'position-parameter' },
  { id: 'TFT-11', officialItem: 'fromTo() 페이지도 "Positioning animations in a timeline" 절을 같은 내용으로 그대로 싣는다. 예제 코드는 tl.to(...) 형태 그대로다.', source: 'timeline-from-to', origin: 'official', sectionId: 'position-parameter' },
  { id: 'TS-10', officialItem: 'set() 페이지만 절 제목이 "Positioning a set() in a timeline"이고, "기본적으로 set() 호출은 timeline 끝에 추가된다"로 문장이 바뀌며 예제 코드도 tl.set(...) 형태다. 나머지 규칙과 예제 값은 동일하다.', source: 'timeline-set', origin: 'official', sectionId: 'position-parameter' },

  // 06 defaults-scope — 2
  { id: 'GT-19', officialItem: 'Setting Defaults — timeline의 defaults 객체에 넣은 것은 자식 animation이 생성될 때 상속된다. 같은 ease나 duration을 계속 반복해 적고 있다면 코드를 간결하게 만들 수 있다. 공식 예제는 세 tween에 duration: 1, ease: "elastic"을 반복해 적은 코드와 defaults로 한 번만 적은 코드를 나란히 보여 준다.', source: 'gsap-timeline', origin: 'official', sectionId: 'defaults-scope' },
  { id: 'GT-20', officialItem: '이렇게 설정한 defaults는 모든 자식 tween에 밀어 넣어지며 특정 property 집합에 한정되지 않는다. 상속된 defaults는 자식 animation에서 그 property를 선언하기만 하면 언제든 쉽게 덮어쓸 수 있다.', source: 'gsap-timeline', origin: 'official', sectionId: 'defaults-scope' },

  // 07 nesting-and-clock — 6
  { id: 'GT-21', officialItem: 'Nesting — timeline 안에 timeline을 원하는 만큼 깊이 중첩할 수 있다. 코드를 모듈화하고 유지보수하기 쉽게 만든다. 공식 예제는 intro() · middle() · conclusion()이 각각 timeline을 반환하고, master timeline이 .add(intro()) · .add(middle(), "+=2") · .add(conclusion(), "-=1")로 이어 붙인다.', source: 'gsap-timeline', origin: 'official', sectionId: 'nesting-and-clock' },
  { id: 'GT-22', officialItem: 'How do timelines work? — 모든 animation(Tween과 Timeline)은 부모 Timeline 위에 놓인다. 어떤 의미에서는 각자 자기 playhead를 가지며(그것이 "time"이 가리키는 것이고 "totalTime"은 repeat와 repeatDelay를 포함한다는 점만 다르다), 부모의 playhead가 새 위치로 옮겨 가면 자식들의 playhead도 갱신된다(자식이 paused가 아닌 한).', source: 'gsap-timeline', origin: 'official', sectionId: 'nesting-and-clock' },
  { id: 'GT-23', officialItem: 'timeline이 특정 시각에 render할 때 자식들을 돌면서 "너는 playhead가 ____에 있는 것처럼 render해"라고 말한다. 그 자식이 다시 자식을 가진 Timeline이면 같은 일을 아래로 계속한다. 그래서 playhead들이 대체로 동기화된 상태를 유지한다.', source: 'gsap-timeline', origin: 'official', sectionId: 'nesting-and-clock' },
  { id: 'GT-24', officialItem: 'animation의 일시정지를 풀면(resume()이나 play()) 내부 playhead가 그 순간 부모 playhead와 동기화되도록 playhead를 집어서 옮긴다. 그래서 완벽하게 매끄럽게 재생된다. 단 timeline의 smoothChildTiming이 false면 그 자식은 움직이지 않고 startTime이 원래 자리에 고정된 채로 남는다.', source: 'gsap-timeline', origin: 'official', sectionId: 'nesting-and-clock' },
  { id: 'GT-25', officialItem: 'smoothChildTiming이 true면 엔진이 playhead가 맞물리도록 실행 중에 배치를 재조정해 재생이 매끄럽게 느껴지게 한다. reverse()하거나 timeScale을 바꿀 때도 마찬가지로 animation의 startTime이 자동으로 이동한다. 하지만 그 동작을 원하지 않을 때가 있고, 그때 부모 timeline에 smoothChildTiming: false가 쓸모 있다.', source: 'gsap-timeline', origin: 'official', sectionId: 'nesting-and-clock' },
  { id: 'GT-26', officialItem: '예시 — root timeline 위에 10초짜리 tween이 있고 2초 지점일 때 tween.seek(5)를 하면 root의 playhead는 영향을 받지 않고 그대로 가지만, 그 tween이 5초로 점프해 제대로 재생되도록 tween의 startTime이 -3으로 바뀐다. 그래야 tween의 playhead와 root playhead가 정확히 맞는다.', source: 'gsap-timeline', origin: 'official', sectionId: 'nesting-and-clock' },

  // 08 boundaries — 11
  { id: 'GT-27', officialItem: 'Other Timeline Features — timeScale() 메서드로 timeline 전체의 속도를 올리거나 낮춘다. 이 값을 tween해서 점진적으로 빨라지거나 느려지게 할 수도 있다.', source: 'gsap-timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'GT-28', officialItem: 'Other Timeline Features — progress()나 totalProgress() 메서드로 timeline의 진행도를 읽거나 설정한다(totalProgress()는 repeat를 포함한다). 절반 지점으로 건너뛰려면 myTimeline.progress(0.5)로 설정한다.', source: 'gsap-timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'GT-29', officialItem: 'Other Timeline Features — time() · totalTime() · progress() · totalProgress()를 tween해서 timeline을 빨리 감거나 되감을 수 있다. 이 중 하나에 slider를 연결하면 사용자가 timeline을 앞뒤로 드래그하게 할 수도 있다.', source: 'gsap-timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'GT-30', officialItem: 'Other Timeline Features — constructor의 vars 객체로 onComplete · onStart · onUpdate · onRepeat · onReverseComplete callback을 추가한다. 예: var tl = gsap.timeline({onComplete: myFunction}).', source: 'gsap-timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'GT-31', officialItem: 'Other Timeline Features — killTweensOf(target)으로 timeline 안 특정 객체의 tween을 kill하고, getTweensOf()로 어떤 객체의 tween을 얻고, getChildren()으로 timeline 안의 모든 tween과 timeline을 얻는다.', source: 'gsap-timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'GT-32', officialItem: 'Other Timeline Features — timeline을 원하는 횟수만큼 또는 무한히 반복하도록 설정할 수 있다. 반복 주기 사이에 delay를 두거나 yoyo로 매 주기 방향이 바뀌는 것처럼 보이게 할 수도 있다.', source: 'gsap-timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'GT-33', officialItem: 'Other Timeline Features — currentLabel()을 얻거나 nextLabel()·previousLabel()로 timeline의 여러 위치에 있는 label을 찾는다.', source: 'gsap-timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'GT-34', officialItem: 'Sample code — gsap.timeline({ repeat: 3, repeatDelay: 1, onComplete: myFunction })으로 만들고 tl.to()로 tween을 추가한 뒤 "+=0.5"로 끝에서 0.5초 뒤에 또 추가하고, tl.reverse(), tl.addLabel("spin", 3), "spin" 위치에 rotation: "+=360" tween 삽입, tl.play("spin"), 그리고 nested timeline을 tl.add(nested, "+=3")으로 넣는 전체 흐름을 한 블록으로 보여 준다.', source: 'gsap-timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'GT-35', officialItem: 'note — gsap.globalTimeline으로 GSAP의 전역 timeline에 접근할 수 있지만 조심해야 한다. 예를 들어 pause()나 timeScale()을 걸면 delayedCall()을 포함한 모든 것에 영향을 준다. 대신 gsap.exportRoot()로 root 위의 기존 animation 전부를(선택적으로 delayedCall은 제외하고) 새 Timeline instance로 감싸 이후에 만들 animation과 분리할 수 있다. 게임 animation을 1/10 속도로 늦추면서 modal animation만 정상 속도로 두고 싶을 때가 딱 그 경우다.', source: 'gsap-timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'TL-10', officialItem: 'Methods 표에는 52개 method가 있고 각 행이 인자와 반환 타입을 밝힌다: add, addLabel, addPause, call, clear, currentLabel, delay, duration, endTime, eventCallback, from, fromTo, getById, getChildren, getTweensOf, globalTime, invalidate, isActive, iteration, kill, killTweensOf, nextLabel, pause, paused, play, previousLabel, progress, recent, remove, removeLabel, removePause, repeat, repeatDelay, restart, resume, reverse, reversed, revert, seek, set, shiftChildren, startTime, then, time, timeScale, to, totalDuration, totalProgress, totalTime, tweenFromTo, tweenTo, yoyo.', source: 'timeline', origin: 'official', sectionId: 'boundaries' },
  { id: 'TL-11', officialItem: 'Methods 표에서 getById( id:String ) : Animation 행만 설명 칸이 비어 있다.', source: 'timeline', origin: 'official', sectionId: 'boundaries' },

  // 공식 문서가 침묵하는 지점 — 실행으로만 확인했고 coverage 분모에 넣지 않는다
  { id: 'TLP-01', officialItem: '인자 없이 gsap.timeline()을 부르면 constructor.name이 "Timeline"이고 gsap.core.Timeline의 instance인 객체가 나오며, vars는 키가 하나도 없는 객체, duration()과 totalDuration()은 0, paused()는 false, parent는 gsap.globalTimeline, "scrollTrigger" in tl은 false다. 공식 문서는 인자 없는 형태의 초기 상태를 밝히지 않는다.', source: 'gsap-timeline', origin: 'implementation', sectionId: 'why-timeline' },
  { id: 'TLP-02', officialItem: 'Timeline의 duration은 직접 정하는 값이 아니라 children에서 파생된다. child를 넣을 때마다 0 → 1 → 3 → 3.5로 따라 커지고, 이미 들어 있는 child의 duration을 1에서 5로 바꾸면 timeline duration도 5가 된다. 공식 문서는 "자동으로 맞춰진다"고만 적고 duration이 파생값이라고 밝히지 않는다.', source: 'gsap-timeline', origin: 'implementation', sectionId: 'timeline-instance' },
  { id: 'TLP-03', officialItem: 'tl.vars는 생성자에 넘긴 바로 그 객체이며(=== 참), Tween과 달리 GSAP이 그 객체에 키를 하나도 추가하지 않는다. {} · {repeat} · {paused, yoyo} · {defaults} · {onComplete} 다섯 조합 모두 생성 전후 키 목록이 같았다. 공식 문서는 복사본인지 원본인지 밝히지 않는다.', source: 'timeline-vars', origin: 'implementation', sectionId: 'timeline-instance' },
  { id: 'TLP-04', officialItem: 'to · from · fromTo · set을 position 있이·없이 총 8번 부른 결과가 모두 timeline 자신이었다(=== 참, 예외 없음). 공식은 "self (makes chaining easier)"라고만 적고 어떤 조합에서도 그런지는 밝히지 않는다.', source: 'timeline-to', origin: 'implementation', sectionId: 'child-creators' },
  { id: 'TLP-05', officialItem: 'defaults는 set() child의 vars에도 들어가지만(ease와 사용자 정의 키가 그대로 남는다) set() child의 duration은 defaults.duration이 0.25 · 1 · 3 어느 값이어도 항상 0이었다. 또 중첩된 Timeline의 자식은 부모의 defaults를 물려받지 않고(손자 duration 0.5 = GSAP 자체 기본값) 중첩 Timeline이 스스로 선언한 defaults만 적용된다(7). 공식은 "모든 자식 tween에 밀어 넣어진다"고만 적는다.', source: 'gsap-timeline', origin: 'implementation', sectionId: 'defaults-scope' },
  { id: 'TLP-06', officialItem: '공식이 나열한 position 표기 23가지를 같은 조건(앞선 1초 child 하나, 0.5초에 "mark" label, 삽입 duration 2초)에서 넣고 child의 startTime을 읽었다. 생략과 "+=0"이 모두 1, "<"가 0, ">"가 1, "<1"이 1, "<+=3"과 "<3"이 모두 3, ">-0.5"가 0.5, "-=25%"가 0.5, "<25%"가 0.25, "<+=25%"가 0.5, "mark+=30%"가 1.1이었다. 없는 label "brandNew"를 적으면 labels에 {"brandNew":1}처럼 timeline 끝 시각으로 등록된다. 공식은 문법만 적고 결과 시각을 적지 않는다.', source: 'timeline-to', origin: 'implementation', sectionId: 'position-parameter' },
  { id: 'TLP-07', officialItem: '"<-2"처럼 결과가 timeline 시작보다 앞이면 child의 startTime이 -2가 되고, 그때 timeline은 duration을 3으로(=-2부터 1까지 전체 폭) 보고한다. 공식은 음수 표기를 예제로 보여 주지만 startTime이 음수가 될 수 있다는 것과 그때 duration이 어떻게 계산되는지는 밝히지 않는다.', source: 'gsap-timeline', origin: 'implementation', sectionId: 'position-parameter' },
  { id: 'TLP-08', officialItem: '10초 child를 먼저 넣고 1초 child를 0초 위치에 넣은 뒤 ">"로 다음 child를 넣으면 startTime이 10이 아니라 1이었다. 공식 각주("가장 최근에 삽입된 animation")가 실제 동작과 일치함을 확인했다.', source: 'timeline-to', origin: 'implementation', sectionId: 'position-parameter' },
  { id: 'TLP-09', officialItem: '재생 중인 timeline에서 첫 child가 0→5로 움직이는 동안, 뒤에 추가한 from() child가 시작값을 먼저 써 버려 약 60ms 시점의 값이 -87.581이었다. 같은 조건에서 set() child는 값을 미리 쓰지 않아 0.601이었다. 공식의 from()/fromTo() immediateRender true 안내와 set()의 immediateRender false 문장이 실제로 그렇게 동작함을 확인했다.', source: 'timeline-from', origin: 'implementation', sectionId: 'child-creators' },
]
