/** 다섯 공식 utility 문서의 기술 item과 GSAP 3.15.0 probe를 학습 섹션에 연결한다. */

/** 이 페이지가 소유하는 공식 source 식별자다. */
export type RangeInterpolationSourceKey = 'clamp' | 'interpolate' | 'map-range' | 'normalize' | 'split-color'

/** 공식 주장과 실행 확인의 출처·상태·로컬 근거를 한 행으로 고정한다. */
export type RangeInterpolationSourceItem = {
  id: string
  officialItem: string
  source: RangeInterpolationSourceKey
  sourceLocation: string
  sourceStatus: 'verified'
  origin: 'official' | 'probe'
  sectionId: string
  localStatus: 'covered'
}

/** 범위 제한부터 색 성분 분리까지 선택하는 데 필요한 공식 49개와 probe 6개다. */
export const rangeInterpolationSourceItems: RangeInterpolationSourceItem[] = [
  { id: 'CL-01', officialItem: 'clamp는 숫자가 minimum보다 작으면 minimum, maximum보다 크면 maximum, 그 사이라면 입력 숫자를 그대로 반환한다.', source: 'clamp', sourceLocation: 'intro', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'CL-08', officialItem: '공식 tip은 재사용 함수를 pipe로 이어 clamp, mapRange, snap, interpolate 같은 여러 변환을 한 입력에 순서대로 적용할 수 있다고 설명한다.', source: 'clamp', sourceLocation: 'Tip: combine reusable functions', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'CL-09', officialItem: '공식 pipeline 예제는 clamp(0, 100) 뒤 mapRange(0, 100, 0, window.innerWidth), snap(20)을 잇고 25.874를 입력한다.', source: 'clamp', sourceLocation: 'Tip example', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'MR-01', officialItem: 'mapRange는 한 범위 안의 상대 위치를 다른 범위의 같은 상대 위치로 옮기며, 공식 문서는 이를 비율처럼 생각하라고 설명한다.', source: 'map-range', sourceLocation: 'intro paragraph 1', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'MR-02', officialItem: '공식 사용 예는 폭 200px slider의 0~200 위치를 0~window.innerWidth에 대응시켜 물체를 화면 좌우로 옮기는 경우다.', source: 'map-range', sourceLocation: 'intro paragraph 2', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'MR-09', officialItem: 'mapRange의 공식 tip도 재사용 함수를 pipe로 이어 clamp, mapRange, snap, interpolate 같은 작업을 합칠 수 있다고 설명한다.', source: 'map-range', sourceLocation: 'Tip: combine reusable functions', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'MR-10', officialItem: 'mapRange의 공식 tip은 clamp(0,100) → mapRange(0,100,0,window.innerWidth) → snap(20) 예제와 utility 조합 영상을 제공한다.', source: 'map-range', sourceLocation: 'Tip example and video demo', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'NO-01', officialItem: 'normalize는 입력 범위 안의 값을 0~1 위치로 옮기며, outMin과 outMax가 0과 1로 고정된 mapRange와 같다.', source: 'normalize', sourceLocation: 'intro', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'NO-08', officialItem: 'normalize의 공식 tip도 재사용 함수를 pipe로 이어 여러 변환을 한 입력에 적용할 수 있다고 설명한다.', source: 'normalize', sourceLocation: 'Tip: combine reusable functions', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'NO-09', officialItem: 'normalize의 공식 tip은 clamp → mapRange → snap 예제와 utility 조합 영상을 제공한다.', source: 'normalize', sourceLocation: 'Tip example and video demo', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'IN-15', officialItem: 'interpolate의 공식 tip은 clamp(0,100) → normalize(0,100) → interpolate("red","blue")를 잇는 colorizer에 25.874를 넣는다.', source: 'interpolate', sourceLocation: 'Tip example', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },
  { id: 'IN-16', officialItem: 'interpolate 페이지는 재사용 utility를 조합하는 별도 영상 demo를 제공한다.', source: 'interpolate', sourceLocation: 'Video demo: combining utility methods', sourceStatus: 'verified', origin: 'official', sectionId: 'pipeline-model', localStatus: 'covered' },

  { id: 'CL-02', officialItem: 'clamp는 valueToClamp를 주면 즉시 값, 생략하면 minimum과 maximum을 기억하는 재사용 함수를 반환하는 두 signature를 제공한다.', source: 'clamp', sourceLocation: 'signature chooser', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'CL-03', officialItem: '즉시 signature는 clamp(minimum:Number, maximum:Number, valueToClamp:Number)다.', source: 'clamp', sourceLocation: '1) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'CL-04', officialItem: '즉시 호출은 잘린 숫자를 반환하며 clamp(0,100,105)는 100, -50은 0, 20은 20이다.', source: 'clamp', sourceLocation: '1) returns and example', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'CL-05', officialItem: '재사용 signature는 clamp(minimum:Number, maximum:Number)다.', source: 'clamp', sourceLocation: '2) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'CL-06', officialItem: 'valueToClamp를 생략하면 값 하나를 받는 함수를 반환하며, 이 함수는 범위를 기억해 여러 번 빠르게 재사용할 수 있다.', source: 'clamp', sourceLocation: '2) returns and explanation', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'CL-07', officialItem: '공식 clamper 예제는 기억한 0~100 범위에 105, -50, 20을 차례로 넣어 100, 0, 20을 얻는다.', source: 'clamp', sourceLocation: '2) example', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'MR-03', officialItem: 'mapRange는 valueToMap을 주면 즉시 값, 생략하면 두 범위를 기억하는 재사용 함수를 반환하는 두 signature를 제공한다.', source: 'map-range', sourceLocation: 'signature chooser', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'MR-04', officialItem: '즉시 signature는 mapRange(inMin:Number, inMax:Number, outMin:Number, outMax:Number, valueToMap:Number)이며 value는 보통 입력 범위 안에 있다.', source: 'map-range', sourceLocation: '1) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'MR-05', officialItem: '즉시 호출은 대응된 숫자를 반환하며 (-10,10)에서 0을 (100,200)에 옮기면 150, (0,100)에서 50을 (0,500)에 옮기면 250이다.', source: 'map-range', sourceLocation: '1) returns and example', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'MR-06', officialItem: '재사용 signature는 mapRange(inMin:Number, inMax:Number, outMin:Number, outMax:Number)다.', source: 'map-range', sourceLocation: '2) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'MR-07', officialItem: 'valueToMap을 생략하면 숫자 하나를 받는 함수를 반환하며, 이 함수는 입력·출력 범위를 기억해 여러 번 재사용할 수 있다.', source: 'map-range', sourceLocation: '2) returns and explanation', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'MR-08', officialItem: '공식 mapper 예제는 mapRange(0,100,0,250)를 기억한 뒤 50과 10을 넣어 125와 25를 얻는다.', source: 'map-range', sourceLocation: '2) example', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'NO-02', officialItem: 'normalize는 valueToNormalize를 주면 즉시 값, 생략하면 입력 범위를 기억하는 재사용 함수를 반환하는 두 signature를 제공한다.', source: 'normalize', sourceLocation: 'signature chooser', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'NO-03', officialItem: '즉시 signature는 normalize(minimum:Number, maximum:Number, valueToNormalize:Number)다.', source: 'normalize', sourceLocation: '1) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'NO-04', officialItem: '즉시 호출은 정규화된 숫자를 반환하며 (-10,10)의 0은 0.5, (0,100)의 25는 0.25다.', source: 'normalize', sourceLocation: '1) returns and example', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'NO-05', officialItem: '재사용 signature는 normalize(minimum:Number, maximum:Number)다.', source: 'normalize', sourceLocation: '2) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'NO-06', officialItem: 'valueToNormalize를 생략하면 값 하나를 받는 함수를 반환하며, 이 함수는 입력 범위를 기억해 여러 번 재사용할 수 있다.', source: 'normalize', sourceLocation: '2) returns and explanation', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'NO-07', officialItem: '공식 예제는 normalize(0,100) 반환 함수의 변수명을 clamper라고 짓고 50, 10, 75를 넣어 0.5, 0.1, 0.75를 얻는다.', source: 'normalize', sourceLocation: '2) example', sourceStatus: 'verified', origin: 'official', sectionId: 'range-contracts', localStatus: 'covered' },

  { id: 'IN-01', officialItem: 'interpolate는 비슷한 타입의 두 값을 선형 보간하며 number, color, string, array, 숫자가 섞인 complex string, 여러 property의 object 등을 지원한다.', source: 'interpolate', sourceLocation: 'intro', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-02', officialItem: 'interpolate는 progress를 주면 즉시 값, 생략하면 나중의 progress를 받는 재사용 함수를 반환한다.', source: 'interpolate', sourceLocation: 'signature chooser', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-03', officialItem: '첫 signature는 interpolate(startValue:*, endValue:*, progress:Number)이며 두 값은 같은 타입이어야 하고 progress 0·0.5·1은 시작·절반·끝이다.', source: 'interpolate', sourceLocation: '1) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-04', officialItem: '첫 signature는 보간된 값을 반환하고, color는 rgba 형식 또는 endValue에서 감지된 경우 hsla 형식으로 반환한다.', source: 'interpolate', sourceLocation: '1) returns', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-05', officialItem: '공식 즉시 예제는 number 0→500의 0.5=250, 20px→40px의 0.5=30px, red→blue의 0.5=rgba(128,0,128,1), object의 각 property 보간을 보여 준다.', source: 'interpolate', sourceLocation: '1) example', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-06', officialItem: '두 번째 signature는 interpolate(array:Array, progress:Number)이며 비슷한 타입의 여러 지점을 순서대로 선형 보간한다.', source: 'interpolate', sourceLocation: '2) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-07', officialItem: '공식 array 예제는 [100,50,500]의 progress 0.5=50·0.75=275, [red,green,blue]의 0.5=green·0.25=rgba(128,64,0,1)을 반환한다.', source: 'interpolate', sourceLocation: '2) returns and example', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-08', officialItem: '세 번째 signature는 progress를 생략한 interpolate(startValue:*, endValue:*)다.', source: 'interpolate', sourceLocation: '3) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-09', officialItem: '세 번째 signature는 progress 하나를 받는 함수를 반환하고, 이 함수는 startValue와 endValue를 기억해 여러 번 재사용할 수 있다.', source: 'interpolate', sourceLocation: '3) returns and explanation', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-10', officialItem: '공식 재사용 예제는 interpolate(0,100)에 0.5·0.25·1을 넣은 결과와 object 두 개를 기억한 함수의 0.5 결과를 보여 준다.', source: 'interpolate', sourceLocation: '3) example', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-11', officialItem: 'object를 보간할 때 별도 내부 object를 만들지 않고 원본 startValue를 변경하려면 세 번째 인자로 true를 줄 수 있다.', source: 'interpolate', sourceLocation: 'mutation note after 3) example', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-12', officialItem: '네 번째 signature는 progress를 생략한 interpolate(array:Array)다.', source: 'interpolate', sourceLocation: '4) signature and parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-13', officialItem: '네 번째 signature는 progress 하나를 받는 함수를 반환하고, 이 함수는 여러 지점 array를 기억해 재사용한다.', source: 'interpolate', sourceLocation: '4) returns and explanation', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'IN-14', officialItem: '공식 array 함수 예제는 [100,50,500]을 기억한 함수의 0.5=50·0.75=275와 color array 함수의 0.25 결과를 보여 준다.', source: 'interpolate', sourceLocation: '4) example', sourceStatus: 'verified', origin: 'official', sectionId: 'interpolation-shapes', localStatus: 'covered' },

  { id: 'SC-01', officialItem: 'splitColor는 문자열 color를 [red, green, blue] 또는 alpha가 필요하면 네 번째 값까지 있는 array로 바꾸며 [255,128,0]과 [255,102,153,0.5]를 반환 예로 든다. 본문 첫 4항 예시는 [255, 0 128, 1]로 comma 하나가 빠져 있다.', source: 'split-color', sourceLocation: 'Returns : Array intro', sourceStatus: 'verified', origin: 'official', sectionId: 'color-components', localStatus: 'covered' },
  { id: 'SC-02', officialItem: '두 번째 인자로 true를 주면 RGB 대신 hue, saturation, lightness와 필요한 경우 alpha 성분을 요청할 수 있다.', source: 'split-color', sourceLocation: 'Returns : Array intro', sourceStatus: 'verified', origin: 'official', sectionId: 'color-components', localStatus: 'covered' },
  { id: 'SC-03', officialItem: 'splitColor는 rgb(), rgba(), hsl(), hsla(), hexadecimal, red·blue 같은 기본 named color를 처리한다.', source: 'split-color', sourceLocation: 'supported formats', sourceStatus: 'verified', origin: 'official', sectionId: 'color-components', localStatus: 'covered' },
  { id: 'SC-04', officialItem: '공식 예제는 red→[255,0,0], #6fb936→[111,185,54], rgba(204,153,51,0.5)→[204,153,51,0.5], #6fb936와 true→[94,55,47]을 보여 준다.', source: 'split-color', sourceLocation: 'examples', sourceStatus: 'verified', origin: 'official', sectionId: 'color-components', localStatus: 'covered' },
  { id: 'SC-05', officialItem: 'Parameters는 color:String과 optional returnHSL:Boolean이며, 반환 type은 Array다.', source: 'split-color', sourceLocation: 'Returns heading and Parameters', sourceStatus: 'verified', origin: 'official', sectionId: 'color-components', localStatus: 'covered' },

  { id: 'RI-P1', officialItem: 'GSAP 3.15.0에서 다섯 페이지의 실행 가능한 공식 예제 결과를 전부 재현했고 값이 일치했다. splitColor 본문 첫 4항 예시는 comma 누락 때문에 그대로는 JavaScript array가 아니며 의도한 실행값은 [255,0,128,1]이다.', source: 'split-color', sourceLocation: 'Node 22 · GSAP 3.15.0 official-example matrix', sourceStatus: 'verified', origin: 'probe', sectionId: 'boundaries', localStatus: 'covered' },
  { id: 'RI-P2', officialItem: 'clamp·mapRange·normalize·두 interpolate 함수 형태는 모두 typeof function이고, 공식 재사용 예제 입력에서 각각 100·125·0.5·25·275를 반환했다.', source: 'clamp', sourceLocation: 'Node 22 · GSAP 3.15.0 reusable-function probe', sourceStatus: 'verified', origin: 'probe', sectionId: 'range-contracts', localStatus: 'covered' },
  { id: 'RI-P3', officialItem: '입력이 범위를 벗어나면 clamp(0,100,-50/150)는 0/100이지만 normalize는 -0.5/1.5, mapRange(0,1,0,360,-0.5/1.5)는 -180/540으로 선형 외삽한다.', source: 'map-range', sourceLocation: 'Node 22 · GSAP 3.15.0 out-of-range probe', sourceStatus: 'verified', origin: 'probe', sectionId: 'boundaries', localStatus: 'covered' },
  { id: 'RI-P4', officialItem: 'progress -0.5/1.5에서 number interpolate는 -180/540, red→blue는 rgba(383,0,-127,1)/rgba(-127,0,383,1)이고, 세 지점 array는 -0.5에서 TypeError지만 1.5에서는 150이다. 공식 0~1 계약 밖 결과는 shape마다 달라 clamp가 필요하다.', source: 'interpolate', sourceLocation: 'Node 22 · GSAP 3.15.0 progress-boundary probe', sourceStatus: 'verified', origin: 'probe', sectionId: 'boundaries', localStatus: 'covered' },
  { id: 'RI-P5', officialItem: 'object interpolate 기본 함수는 start object와 다른 새 결과를 반환해 원본을 보존하고, 세 번째 인자 true를 준 함수는 start와 같은 참조를 반환하며 원본 property를 바꾼다.', source: 'interpolate', sourceLocation: 'Node 22 · GSAP 3.15.0 identity probe', sourceStatus: 'verified', origin: 'probe', sectionId: 'interpolation-shapes', localStatus: 'covered' },
  { id: 'RI-P6', officialItem: '길이 0인 normalize(5,5,5)와 mapRange(5,5,0,100,5)는 0이고, 역방향 normalize(100,0,25)는 0.75지만 clamp(100,0,50)는 100이다. 공식 lower/upper·minimum/maximum 순서를 지키는 것이 안전하다.', source: 'normalize', sourceLocation: 'Node 22 · GSAP 3.15.0 degenerate-range probe', sourceStatus: 'verified', origin: 'probe', sectionId: 'boundaries', localStatus: 'covered' },
]
