/** 세 공식 생성 method의 21개 source item과 로컬 근거 목표를 고정한다. */
export const tweenStartEndValuesReference = [
  { id: 'TSV-FR-001', item: 'gsap.from(targets, vars): Tween', evidence: '#from-and-from-to' },
  { id: 'TSV-FR-002', item: 'from은 vars를 시작값으로, 현재 상태를 끝값으로 쓴다.', evidence: '#state-ownership' },
  { id: 'TSV-FR-003', item: 'target은 selector, element, object, object array가 될 수 있다.', evidence: '#from-and-from-to' },
  { id: 'TSV-FR-004', item: '반환 Tween으로 재생을 제어하며 기본 재생·완료 정리 lifecycle을 공유한다.', evidence: '#from-and-from-to' },
  { id: 'TSV-FR-005', item: 'to, from, fromTo는 값 소유권이 다르다.', evidence: '#state-ownership' },
  { id: 'TSV-FR-006', item: 'vars에는 animation 값과 special property가 함께 들어간다.', evidence: '#from-and-from-to' },
  { id: 'TSV-FR-007', item: 'from의 immediateRender 기본값은 true다.', evidence: '#immediate-render' },
  { id: 'TSV-FR-008', item: 'FOUC 대응과 from 반복 생성 오용 경계를 설명한다.', evidence: '#immediate-render, #choose' },
  { id: 'TSV-FT-001', item: 'gsap.fromTo(targets, fromVars, toVars): Tween', evidence: '#from-and-from-to' },
  { id: 'TSV-FT-002', item: 'positional duration overload 대신 vars의 duration을 쓴다.', evidence: '#from-and-from-to' },
  { id: 'TSV-FT-003', item: 'fromTo는 현재 상태와 무관하게 양 끝을 명시한다.', evidence: '#state-ownership' },
  { id: 'TSV-FT-004', item: 'special property는 toVars에 둔다.', evidence: '#from-and-from-to' },
  { id: 'TSV-FT-005', item: 'fromTo의 target, Tween 제어, lifecycle은 from과 같다.', evidence: '#method-comparison' },
  { id: 'TSV-FT-006', item: 'fromTo의 immediateRender 기본값은 true다.', evidence: '#immediate-render' },
  { id: 'TSV-SET-001', item: 'gsap.set(targets, vars): Tween', evidence: '#set' },
  { id: 'TSV-SET-002', item: 'set은 duration 0인 Tween과 같은 즉시 설정이다.', evidence: '#state-ownership' },
  { id: 'TSV-SET-003', item: 'selector나 array로 여러 target을 설정할 수 있다.', evidence: '#set' },
  { id: 'TSV-SET-004', item: '반복 고빈도 설정은 quickSetter 경계다.', evidence: '#set' },
  { id: 'TSV-SHARED-001', item: 'special properties catalog는 gsap.to owner를 참조한다.', evidence: '#shared-vars' },
  { id: 'TSV-SHARED-002', item: 'plugin, function, random, relative, stagger는 공통 value mode다.', evidence: '#shared-vars' },
  { id: 'TSV-SHARED-003', item: '복잡한 sequence와 callback은 각 owner를 참조한다.', evidence: '#shared-vars' },
] as const
