/** 두 child sequence의 전체 회차와 yoyo 역순을 조작·관찰·코드로 함께 보여준다. */
import { useSequenceCycleRuntime } from './useSequenceCycleRuntime'
import { RepoFileLink } from '../../../../../../components/demo/RepoFileLink/RepoFileLink'
import './SequenceCycleLab.css'

export function SequenceCycleLab() {
  // runtime이 소유한 descriptor와 실제 getter snapshot을 화면에만 쓴다
  const { scope, repeat, setRepeat, repeatDelay, setRepeatDelay, yoyo, setYoyo, totalProgress, setTotalProgress, descriptor, observation, reducedMotion } = useSequenceCycleRuntime()
  // repeat + 1개의 회차 라벨을 표시 순서로 만든다
  const iterations = Array.from({ length: repeat + 1 }, (_, index) => index + 1)
  // 실행 descriptor와 getter 결과를 그대로 직렬화해 표시 코드를 만든다
  const code = `const tl = gsap.timeline({\n  paused: true,\n  repeat: ${descriptor.repeat},\n  repeatDelay: ${descriptor.repeatDelay},\n  yoyo: ${descriptor.yoyo},\n  defaults: { duration: ${descriptor.childDuration}, ease: 'none' },\n})\n\ntl.to('${descriptor.firstSelector}', { x: ${descriptor.distance} })\n  .to('${descriptor.secondSelector}', { x: ${descriptor.distance} })\n\ntl.totalProgress(${descriptor.totalProgress}, true)\ntl.iteration() // ${observation.iteration}`

  return <section className={`sequence-cycle-lab${reducedMotion ? ' sequence-cycle-lab--static' : ''}`} aria-labelledby="sequence-cycle-lab-title"><h3 id="sequence-cycle-lab-title">A → B sequence의 회차를 직접 훑기</h3><p className="sequence-cycle-lab__goal">자동 재생 없이 totalProgress slider로 전체 반복 시간표를 움직입니다. yoyo 회차에서 B가 먼저 되감기는지 두 숫자를 보세요.</p><div className="sequence-cycle-lab__body" ref={scope}><div className="sequence-cycle-lab__stage"><div className="sequence-cycle-lab__lane"><span>A</span><div className="sequence-cycle-lab__box sequence-cycle-lab__box--a">A</div></div><div className="sequence-cycle-lab__lane"><span>B</span><div className="sequence-cycle-lab__box sequence-cycle-lab__box--b">B</div></div></div><fieldset className="sequence-cycle-lab__controls"><legend>Timeline 반복 설정</legend><label htmlFor="sequence-total-progress">totalProgress · {totalProgress}</label><input id="sequence-total-progress" type="range" min="0" max="1" step="0.01" value={totalProgress} onChange={(event) => setTotalProgress(Number(event.target.value))}/><label htmlFor="sequence-repeat">repeat · {repeat}</label><input id="sequence-repeat" type="range" min="0" max="3" step="1" value={repeat} onChange={(event) => setRepeat(Number(event.target.value))}/><label htmlFor="sequence-repeat-delay">repeatDelay · {repeatDelay}s</label><input id="sequence-repeat-delay" type="range" min="0" max="1" step="0.25" value={repeatDelay} onChange={(event) => setRepeatDelay(Number(event.target.value))}/><label><input type="checkbox" checked={yoyo} onChange={(event) => setYoyo(event.target.checked)}/> yoyo</label></fieldset></div><ol className="sequence-cycle-lab__strip" aria-label="sequence 반복 회차">{iterations.map((iteration) => <li key={iteration} className={iteration === observation.iteration ? 'sequence-cycle-lab__iteration--active' : ''}><strong>{iteration}회차</strong><span>{yoyo && iteration % 2 === 0 ? 'B → A' : 'A → B'}</span></li>)}</ol><dl className="sequence-cycle-lab__readout"><div><dt>iteration()</dt><dd>{observation.iteration}</dd></div><div><dt>time / totalTime</dt><dd>{observation.time} / {observation.totalTime}</dd></div><div><dt>duration / totalDuration</dt><dd>{observation.duration} / {observation.totalDuration}</dd></div><div><dt>A x / B x</dt><dd>{observation.firstX} / {observation.secondX}</dd></div><div><dt>reversed()</dt><dd>{String(observation.reversed)}</dd></div></dl><pre className="sequence-cycle-lab__code"><code>{code}</code></pre><p className="sequence-cycle-lab__source">실행 코드 위치 · <RepoFileLink path="src/content/gsap/fundamentals/timeline-repeats/examples/SequenceCycleLab/useSequenceCycleRuntime.ts" /></p></section>
}
