/** gsap.effects와 registerEffect의 공식 17개·설치본 구현 4개 item을 로컬 section evidence에 연결한다. */
export const reusableEffectsCatalog = [
  { id: 'RE-EFFECTS-TYPE', item: 'gsap.effects는 등록된 effect를 보관하는 object다.', origin: 'official', evidence: '#direct-call' },
  { id: 'RE-EFFECTS-NAMED-ACCESS', item: '등록 name으로 gsap.effects[name](targets, config?)를 호출한다.', origin: 'official', evidence: '#direct-call' },
  { id: 'RE-EFFECTS-DIRECT-RETURN', item: 'direct 호출은 effect callback의 반환값을 그대로 돌려준다.', origin: 'implementation', evidence: '#registered-example' },
  { id: 'RE-REGISTER-SHAPE', item: '공식 등록 예제는 name, effect, defaults, extendTimeline을 설정한다.', origin: 'official', evidence: '#register-contract' },
  { id: 'RE-REGISTER-RETURN', item: '설치된 타입에서 registerEffect() 반환 타입은 void이고 실행 결과는 undefined다.', origin: 'implementation', evidence: '#register-contract' },
  { id: 'RE-REGISTER-NAME', item: 'name은 gsap.effects의 key이자 확장한 Timeline method 이름이다.', origin: 'official', evidence: '#register-contract' },
  { id: 'RE-REGISTER-EFFECT', item: 'effect callback은 targets와 config를 받는다.', origin: 'official', evidence: '#register-contract' },
  { id: 'RE-REGISTER-TARGETS', item: 'selector, target, group은 callback 전에 target array로 정규화된다.', origin: 'official', evidence: '#direct-call' },
  { id: 'RE-REGISTER-CONFIG', item: '호출할 때마다 config가 callback에 전달된다.', origin: 'official', evidence: '#register-contract' },
  { id: 'RE-REGISTER-DEFAULTS', item: 'defaults는 빠진 key를 채우고 명시한 호출값이 우선한다.', origin: 'official', evidence: '#registered-example' },
  { id: 'RE-REGISTER-CENTRAL', item: 'effect는 gsap.effects에서 새 targets와 config로 재사용된다.', origin: 'official', evidence: '#mental-model' },
  { id: 'RE-EXTEND-OPTION', item: 'extendTimeline true는 Timeline prototype에 동명 method를 추가한다.', origin: 'official', evidence: '#timeline-extension' },
  { id: 'RE-TIMELINE-SIGNATURE', item: '공식 확장 예제는 targets, config, position 순서로 호출한다.', origin: 'official', evidence: '#timeline-extension' },
  { id: 'RE-TIMELINE-ADD', item: '확장 method는 반환 animation을 선택한 position에 삽입한다.', origin: 'official', evidence: '#timeline-extension' },
  { id: 'RE-TIMELINE-RETURN', item: '공식 예제는 확장 method 뒤에 effect와 Tween을 계속 chaining한다.', origin: 'official', evidence: '#timeline-extension' },
  { id: 'RE-TIMELINE-CONTEXT', item: '설치본 callback의 세 번째 인자는 호출한 parent Timeline이다.', origin: 'implementation', evidence: '#timeline-extension' },
  { id: 'RE-TIMELINE-POSITION-SHORTHAND', item: '설치본은 두 번째 인자가 object가 아니면 position으로 취급하고 defaults를 쓴다.', origin: 'implementation', evidence: '#timeline-extension' },
  { id: 'RE-EXTEND-RETURN-WARNING', item: '확장 effect는 Timeline에 넣을 Tween이나 Timeline을 반환해야 한다.', origin: 'official', evidence: '#timeline-extension' },
  { id: 'RE-NONEXTEND-ADD', item: '확장 없이도 direct effect 결과를 tl.add로 삽입할 수 있다.', origin: 'official', evidence: '#boundaries' },
  { id: 'RE-OFFICIAL-FADE', item: '공식 fade 예제는 duration 기본값 2, override, Timeline chaining과 position을 보여준다.', origin: 'official', evidence: '#direct-call' },
  { id: 'RE-EFFECTS-PORTABLE', item: '등록 effect는 targets와 config를 바꿔 프로젝트 간에 공유할 수 있다.', origin: 'official', evidence: '#mental-model' },
] as const
